version: '3.8'
services:
  app:
    build:
      context: .
    environment:
      - PUID=1000
      - PGID=1000
      - AUTORUN_ENABLED=true
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
